############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Contact us"
url = "contact/"
weight = 2

# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "Contact us"
url = "contact/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
