############# Czech navigation ##############

# main menu
[[main]]
name = "Domu"
url = "/"
weight = 1

[[main]]
name = "Samply"
url = "samples/"
weight = 2

[[main]]
name = "Kontaktujte nás"
url = "contact/"
weight = 3

# footer menu
[[footer]]
name = "Domu"
url = "/"
weight = 1

[[footer]]
name = "Samply"
url = "samples/"
weight = 2

[[footer]]
name = "Kontaktujte nás"
url = "contact/"
weight = 3
