############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Samples"
url = "samples/"
weight = 2

[[main]]
name = "Contact us"
url = "contact/"
weight = 3

# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "Samples"
url = "samples/"
weight = 2

[[footer]]
name = "Contact us"
url = "contact/"
weight = 3

[[footer]]
name = "Privacy policy"
url = "privacy-policy/"
weight = 4
